### ISSUE TITLE
show image created date in statusbar

### ISSUE THREAD

**Issue by allanlaal** [xiongchiamiov/Mirage#2]
show image created date in statusbar next to filename and resolution

**Comment by xiongchiamiov** [comment]
Hi.  This is just a mirror of Mirage (and probably very outdated), created to make it easier for me to integrate it with some git project at some point in time.  I no longer use Mirage and have no interest in (or really, qualification for) maintaining it.

I would suggest contacting [the project authors](http://sourceforge.net/projects/mirageiv/).  Thanks!
